"""Typed records and NumPy dtypes shared by future simulation stages."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from enum import IntEnum, StrEnum
from types import MappingProxyType
from typing import Any

import numpy as np
import numpy.typing as npt

from he3sim.config import ParameterStatus

FloatArray = npt.NDArray[np.float32]
Float64Array = npt.NDArray[np.float64]
IntegerArray = npt.NDArray[np.signedinteger[Any]]
Int16Array = npt.NDArray[np.int16]
UInt16Array = npt.NDArray[np.uint16]
BooleanArray = npt.NDArray[np.bool_]


class Polarity(IntEnum):
    """Pulse polarity stored independently from positive peak magnitude."""

    NEGATIVE = -1
    POSITIVE = 1


class RejectionReason(StrEnum):
    """Reserved observation-layer rejection categories."""

    NONE = "none"
    DEAD_TIME = "dead_time"
    BELOW_THRESHOLD = "below_threshold"
    SATURATED = "saturated"


@dataclass(frozen=True, slots=True)
class SpectrumSamples:
    """Deposited energies and their parameterized spectrum component IDs."""

    energy_dep_keV: Float64Array
    component_id: Int16Array

    def __post_init__(self) -> None:
        """Require aligned one-dimensional arrays."""
        if self.energy_dep_keV.ndim != 1 or self.component_id.ndim != 1:
            raise ValueError("spectrum sample arrays must be one-dimensional")
        if self.energy_dep_keV.shape != self.component_id.shape:
            raise ValueError("spectrum sample arrays must have matching shapes")


@dataclass(frozen=True, slots=True)
class AmplitudeSamples:
    """Positive peak magnitudes and separately stored pulse polarities."""

    amplitude_peak_V: Float64Array
    polarity: Int16Array

    def __post_init__(self) -> None:
        """Require aligned one-dimensional arrays."""
        if self.amplitude_peak_V.ndim != 1 or self.polarity.ndim != 1:
            raise ValueError("amplitude sample arrays must be one-dimensional")
        if self.amplitude_peak_V.shape != self.polarity.shape:
            raise ValueError("amplitude sample arrays must have matching shapes")


@dataclass(frozen=True, slots=True)
class PulseParameterSamples:
    """Aligned positive double-exponential time constants for truth events."""

    tau_r_s: Float64Array
    tau_d_s: Float64Array

    def __post_init__(self) -> None:
        """Require aligned vectors satisfying ``tau_d_s > tau_r_s > 0``."""
        if self.tau_r_s.ndim != 1 or self.tau_d_s.ndim != 1:
            raise ValueError("pulse-parameter arrays must be one-dimensional")
        if self.tau_r_s.shape != self.tau_d_s.shape:
            raise ValueError("pulse-parameter arrays must have matching shapes")
        if np.any(~np.isfinite(self.tau_r_s)) or np.any(~np.isfinite(self.tau_d_s)):
            raise ValueError("pulse-parameter arrays must be finite")
        if np.any(self.tau_r_s <= 0.0) or np.any(self.tau_d_s <= self.tau_r_s):
            raise ValueError("pulse parameters must satisfy tau_d_s > tau_r_s > 0")


@dataclass(frozen=True, slots=True)
class TrueEvent:
    """One truth-layer event record generated by Phase 1."""

    event_id: int
    t_s: float
    energy_dep_keV: float
    spectrum_component_id: int
    amplitude_peak_V: float
    tau_r_s: float
    tau_d_s: float
    polarity: Polarity
    block_id: int
    sample_index: int
    pileup_group_id: int
    parameter_status: ParameterStatus


@dataclass(frozen=True, slots=True)
class WaveformBlock:
    """One bounded Phase 2 continuous-waveform block."""

    block_id: int
    sample_index_start: int
    t_start_s: float
    sample_rate_hz: float
    preclip_analog_samples_V: FloatArray | None = None
    analog_samples_V: FloatArray | None = None
    adc_samples: UInt16Array | None = None
    saturation_mask: BooleanArray | None = None

    def __post_init__(self) -> None:
        """Require aligned arrays and finite non-negative block metadata."""
        if self.block_id < 0 or self.sample_index_start < 0:
            raise ValueError("block identifiers and sample offsets must be non-negative")
        if not np.isfinite(self.t_start_s) or self.t_start_s < 0.0:
            raise ValueError("t_start_s must be finite and non-negative")
        if not np.isfinite(self.sample_rate_hz) or self.sample_rate_hz <= 0.0:
            raise ValueError("sample_rate_hz must be finite and positive")
        arrays = [
            array
            for array in (
                self.preclip_analog_samples_V,
                self.analog_samples_V,
                self.adc_samples,
                self.saturation_mask,
            )
            if array is not None
        ]
        if not arrays:
            raise ValueError("waveform block must contain at least one sample array")
        if any(array.ndim != 1 for array in arrays):
            raise ValueError("waveform block arrays must be one-dimensional")
        if len({array.shape for array in arrays}) != 1:
            raise ValueError("waveform block arrays must have matching shapes")


@dataclass(frozen=True, slots=True)
class ObservedEvent:
    """One observation-layer event record after future triggering and dead time."""

    trigger_id: int
    trigger_time_s: float
    accepted: bool
    rejection_reason: RejectionReason
    peak_adc: int
    peak_V: float
    integral_V_s: float
    rise_time_10_90_s: float
    fall_time_90_10_s: float
    is_pileup: bool
    is_saturated: bool


@dataclass(frozen=True, slots=True)
class CalibrationMetadata:
    """Serializable provenance required alongside future calibrated outputs."""

    config_hash: str
    code_version: str
    seed: int
    parameter_status: ParameterStatus
    units: Mapping[str, str]
    source: str | None = None

    def __post_init__(self) -> None:
        """Freeze a defensive copy of the units mapping."""
        object.__setattr__(self, "units", MappingProxyType(dict(self.units)))

    def to_serializable_dict(self) -> dict[str, int | str | dict[str, str] | None]:
        """Return JSON-compatible calibration provenance without mutable aliases."""
        return {
            "config_hash": self.config_hash,
            "code_version": self.code_version,
            "seed": self.seed,
            "parameter_status": self.parameter_status.value,
            "units": dict(self.units),
            "source": self.source,
        }


TRUE_EVENT_DTYPE = np.dtype(
    [
        ("event_id", "<i8"),
        ("t_s", "<f8"),
        ("energy_dep_keV", "<f8"),
        ("spectrum_component_id", "<i2"),
        ("amplitude_peak_V", "<f8"),
        ("tau_r_s", "<f8"),
        ("tau_d_s", "<f8"),
        ("polarity", "i1"),
        ("block_id", "<i8"),
        ("sample_index", "<i8"),
        ("pileup_group_id", "<i8"),
        ("parameter_status", "S16"),
    ]
)
"""Structured dtype for future bulk truth-event storage."""


OBSERVED_EVENT_DTYPE = np.dtype(
    [
        ("trigger_id", "<i8"),
        ("trigger_time_s", "<f8"),
        ("accepted", "?"),
        ("rejection_reason", "S32"),
        ("peak_adc", "<i8"),
        ("peak_V", "<f8"),
        ("integral_V_s", "<f8"),
        ("rise_time_10_90_s", "<f8"),
        ("fall_time_90_10_s", "<f8"),
        ("is_pileup", "?"),
        ("is_saturated", "?"),
    ]
)
"""Structured dtype for bulk Phase 3 observed-event storage."""


TRIGGER_EVENT_LINK_DTYPE = np.dtype(
    [
        ("trigger_id", "<i8"),
        ("event_id", "<i8"),
        ("event_time_offset_s", "<f8"),
    ]
)
"""Many-to-many trigger-to-truth association rows."""


WINDOW_METADATA_DTYPE = np.dtype(
    [
        ("window_id", "<i8"),
        ("trigger_id", "<i8"),
        ("sample_index_start", "<i8"),
        ("trigger_sample_offset", "<i8"),
        ("sample_rate_hz", "<f8"),
        ("is_saturated", "?"),
    ]
)
"""Fixed-length accepted-trigger window index."""


WAVEFORM_BLOCK_INDEX_DTYPE = np.dtype(
    [
        ("block_id", "<i8"),
        ("offset", "<i8"),
        ("length", "<i8"),
        ("t_start_s", "<f8"),
        ("sample_rate_hz", "<f8"),
        ("event_count", "<i8"),
    ]
)
"""Structured dtype for concatenated Phase 2 waveform block metadata."""
